<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Compile Remove="Models\Dto\**" />
    <Compile Remove="Utilities\**" />
    <Content Remove="Data\**" />
    <Content Remove="Models\Dto\**" />
    <Content Remove="Utilities\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Models\Dto\**" />
    <EmbeddedResource Remove="Utilities\**" />
    <None Remove="Data\**" />
    <None Remove="Models\Dto\**" />
    <None Remove="Utilities\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="reports\Admissionreport.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\NursingCare\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\lib\jquery-validation\" />
    <Folder Include="wwwroot\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\lib\jquery\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Discharge\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Shared\Components\DailyObservation\Default.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Shared\Components\ClinicalAssessment\Default.cshtml" />
    <_ContentIncludedByDefault Remove="Views\DeathCertificates\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Admissions\AdmissionDischargeDetail.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Surgeries\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Surgeries\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Shared\Components\ClientInfo\Client.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Shared\Components\ClientInfo\Default.cshtml" />
    <_ContentIncludedByDefault Remove="Views\DoctorsNote\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\DoctorsNote\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Discharge\Details.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Discharge\DischargeNoteList.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Discharge\DischargeNoteList.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\DoctorsNote\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\DoctorsNote\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Shared\Components\ClientInfo\Default.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Shared\Components\ClientInfo\Client.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Surgeries\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Surgeries\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Admissions\AdmissionDischargeDetail.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPD.Domain\IPD.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\DeathCertificates\Create.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Shared\Components\ClinicalAssessment\Default.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Shared\Components\DailyObservation\Default.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="reports\Admissionreport.rdlc" />
  </ItemGroup>

</Project>
